{% set name = "aioftp" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b5a412c748722dd679c4c2e30dd40d70a7c8879636f6eb4489fdbca72965b125

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - aioftp

about:
  home: http://aioftp.readthedocs.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: license.txt
  summary: FTP client/server for Python asyncio
  dev_url: https://github.com/aio-libs/aioftp

extra:
  recipe-maintainers:
    - epruesse
    - nabobalis
    - cadair
