{% set name = "aioftp" %}
{% set version = "0.25.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8402efe0d4783b9c4d6787446d5e027abe79796951f227241bd2c5d8f3e09d0b

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - aioftp

about:
  home: http://aioftp.readthedocs.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: license.txt
  summary: FTP client/server for Python asyncio
  dev_url: https://github.com/aio-libs/aioftp

extra:
  recipe-maintainers:
    - epruesse
    - nabobalis
    - cadair
